[project]
name = "bloomfilter"
version = "1.0.1"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Bloom filter implementation"
license = "ISC"
repository = "https://github.com/sga001/rust-bloom-filter"

[lib]

[dependencies]
bit-vec = "0.4.4"
rand = "0.4.1"
metrohash = "1.0.5"
